#Nombre del workflows (Aparece en la UI)
name: CI Pipeline
#Eventos que dispara el workflows
on:
  push:
    branches: [main, develop]

#Jobs a ejecutar
jobs:
  #Id de job
  build:
    #Runner a usar
    runs-on: ubuntu-latest
    #Steps del jobs
    steps:
      #Step1 : Checkout codigo
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setups-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm Install 
