name: CI
on:
  push:
    branchs: [secrets]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version
        env:
          NODE_VERSION: 24
        run: echo Node version:  ${{env.NODE_VERSION}}